//
// Dark Souls 3 - Open Server
// Copyright (C) 2021 Tim Leonard
//
// This program is free software; licensed under the MIT license.
// You should have received a copy of the license along with this program.
// If not, see <https://opensource.org/licenses/MIT>.

// Credit: A lot of information here has been derived from the protobufs of AmirBohd's ModEngine2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: Shared_Frpg2RequestMessage.proto

package sharedpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// First message sent to the login server, used to request
// the port and server_ip to authenticate over.
// LOCAL DIVERGENCE FROM THE REFERENCE SCHEMA
// The fields FromSoftware named `steam_id` / `player_steam_id` are renamed here
// to `psn_id` / `player_psn_id`. This project targets Dark Souls 2 on PS3, where
// that field carries the PSN online ID; the Steam naming is an artifact of the
// reference having been reversed from the PC build.
//
// This is a NAME change only. Field numbers and wire types are untouched, so the
// wire format is identical and captures remain comparable with the reference.
// Everything else in this file is kept pristine for diffing against ref/ds3so.
type RequestQueryLoginServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PsnId         *string                `protobuf:"bytes,1,req,name=psn_id,json=psnId" json:"psn_id,omitempty"`
	F2            *string                `protobuf:"bytes,2,opt,name=f2" json:"f2,omitempty"`
	AppVersion    *uint64                `protobuf:"varint,3,req,name=app_version,json=appVersion" json:"app_version,omitempty"` // app version without the period and -1. eg. app ver 1.13 = 112
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestQueryLoginServerInfo) Reset() {
	*x = RequestQueryLoginServerInfo{}
	mi := &file_Shared_Frpg2RequestMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestQueryLoginServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestQueryLoginServerInfo) ProtoMessage() {}

func (x *RequestQueryLoginServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_Frpg2RequestMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestQueryLoginServerInfo.ProtoReflect.Descriptor instead.
func (*RequestQueryLoginServerInfo) Descriptor() ([]byte, []int) {
	return file_Shared_Frpg2RequestMessage_proto_rawDescGZIP(), []int{0}
}

func (x *RequestQueryLoginServerInfo) GetPsnId() string {
	if x != nil && x.PsnId != nil {
		return *x.PsnId
	}
	return ""
}

func (x *RequestQueryLoginServerInfo) GetF2() string {
	if x != nil && x.F2 != nil {
		return *x.F2
	}
	return ""
}

func (x *RequestQueryLoginServerInfo) GetAppVersion() uint64 {
	if x != nil && x.AppVersion != nil {
		return *x.AppVersion
	}
	return 0
}

// Send in response to RequestQueryLoginServerInfo
type RequestQueryLoginServerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          *int64                 `protobuf:"varint,1,req,name=port" json:"port,omitempty"`
	ServerIp      *string                `protobuf:"bytes,2,req,name=server_ip,json=serverIp" json:"server_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestQueryLoginServerInfoResponse) Reset() {
	*x = RequestQueryLoginServerInfoResponse{}
	mi := &file_Shared_Frpg2RequestMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestQueryLoginServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestQueryLoginServerInfoResponse) ProtoMessage() {}

func (x *RequestQueryLoginServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_Frpg2RequestMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestQueryLoginServerInfoResponse.ProtoReflect.Descriptor instead.
func (*RequestQueryLoginServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_Shared_Frpg2RequestMessage_proto_rawDescGZIP(), []int{1}
}

func (x *RequestQueryLoginServerInfoResponse) GetPort() int64 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *RequestQueryLoginServerInfoResponse) GetServerIp() string {
	if x != nil && x.ServerIp != nil {
		return *x.ServerIp
	}
	return ""
}

// Presumably a message sent instead of RequestQueryLoginServerInfo on xbox
// Probably holds an xbox-specific user-id.
type RequestQueryLoginServerInfoForXboxOne struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestQueryLoginServerInfoForXboxOne) Reset() {
	*x = RequestQueryLoginServerInfoForXboxOne{}
	mi := &file_Shared_Frpg2RequestMessage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestQueryLoginServerInfoForXboxOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestQueryLoginServerInfoForXboxOne) ProtoMessage() {}

func (x *RequestQueryLoginServerInfoForXboxOne) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_Frpg2RequestMessage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestQueryLoginServerInfoForXboxOne.ProtoReflect.Descriptor instead.
func (*RequestQueryLoginServerInfoForXboxOne) Descriptor() ([]byte, []int) {
	return file_Shared_Frpg2RequestMessage_proto_rawDescGZIP(), []int{2}
}

// First message sent to auth server RSA encrypted. Provides a CWC key used
// for encrypting the rest of the traffic.
type RequestHandshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AesCwcKey     []byte                 `protobuf:"bytes,1,req,name=aes_cwc_key,json=aesCwcKey" json:"aes_cwc_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestHandshake) Reset() {
	*x = RequestHandshake{}
	mi := &file_Shared_Frpg2RequestMessage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHandshake) ProtoMessage() {}

func (x *RequestHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_Frpg2RequestMessage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHandshake.ProtoReflect.Descriptor instead.
func (*RequestHandshake) Descriptor() ([]byte, []int) {
	return file_Shared_Frpg2RequestMessage_proto_rawDescGZIP(), []int{3}
}

func (x *RequestHandshake) GetAesCwcKey() []byte {
	if x != nil {
		return x.AesCwcKey
	}
	return nil
}

// Response to initial message, encrypted with CWC.
type RequestHandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestHandshakeResponse) Reset() {
	*x = RequestHandshakeResponse{}
	mi := &file_Shared_Frpg2RequestMessage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHandshakeResponse) ProtoMessage() {}

func (x *RequestHandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_Frpg2RequestMessage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHandshakeResponse.ProtoReflect.Descriptor instead.
func (*RequestHandshakeResponse) Descriptor() ([]byte, []int) {
	return file_Shared_Frpg2RequestMessage_proto_rawDescGZIP(), []int{4}
}

// Sent after handshake, all seemingly constant data (apart from the steam_id).
// Presumably used for ensure we are connecting to a compatible server?
type GetServiceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	PsnId         *string                `protobuf:"bytes,2,req,name=psn_id,json=psnId" json:"psn_id,omitempty"`
	Unknown_1     *string                `protobuf:"bytes,3,opt,name=unknown_1,json=unknown1" json:"unknown_1,omitempty"`
	AppVersion    *int64                 `protobuf:"varint,4,req,name=app_version,json=appVersion" json:"app_version,omitempty"` // 1.15 = 114 (zero indexed)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceStatus) Reset() {
	*x = GetServiceStatus{}
	mi := &file_Shared_Frpg2RequestMessage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceStatus) ProtoMessage() {}

func (x *GetServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_Frpg2RequestMessage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceStatus.ProtoReflect.Descriptor instead.
func (*GetServiceStatus) Descriptor() ([]byte, []int) {
	return file_Shared_Frpg2RequestMessage_proto_rawDescGZIP(), []int{5}
}

func (x *GetServiceStatus) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *GetServiceStatus) GetPsnId() string {
	if x != nil && x.PsnId != nil {
		return *x.PsnId
	}
	return ""
}

func (x *GetServiceStatus) GetUnknown_1() string {
	if x != nil && x.Unknown_1 != nil {
		return *x.Unknown_1
	}
	return ""
}

func (x *GetServiceStatus) GetAppVersion() int64 {
	if x != nil && x.AppVersion != nil {
		return *x.AppVersion
	}
	return 0
}

// Same as above but probably has an xbox one id rather than steam_id.
type GetServiceStatusForXboxOne struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceStatusForXboxOne) Reset() {
	*x = GetServiceStatusForXboxOne{}
	mi := &file_Shared_Frpg2RequestMessage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceStatusForXboxOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceStatusForXboxOne) ProtoMessage() {}

func (x *GetServiceStatusForXboxOne) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_Frpg2RequestMessage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceStatusForXboxOne.ProtoReflect.Descriptor instead.
func (*GetServiceStatusForXboxOne) Descriptor() ([]byte, []int) {
	return file_Shared_Frpg2RequestMessage_proto_rawDescGZIP(), []int{6}
}

// Response to GetServiceStatus, contains identical data to what is sent
// with the exception of a blank steam_id. Presumably if we connected to a dev server
// or something we would get different responses.
// If we are on an older version of the game an empty response is sent back for this.
type GetServiceStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	PsnId         *string                `protobuf:"bytes,2,opt,name=psn_id,json=psnId" json:"psn_id,omitempty"`
	Unknown_1     *int64                 `protobuf:"varint,3,opt,name=unknown_1,json=unknown1" json:"unknown_1,omitempty"`
	AppVersion    *int64                 `protobuf:"varint,4,opt,name=app_version,json=appVersion" json:"app_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceStatusResponse) Reset() {
	*x = GetServiceStatusResponse{}
	mi := &file_Shared_Frpg2RequestMessage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceStatusResponse) ProtoMessage() {}

func (x *GetServiceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_Frpg2RequestMessage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceStatusResponse.ProtoReflect.Descriptor instead.
func (*GetServiceStatusResponse) Descriptor() ([]byte, []int) {
	return file_Shared_Frpg2RequestMessage_proto_rawDescGZIP(), []int{7}
}

func (x *GetServiceStatusResponse) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *GetServiceStatusResponse) GetPsnId() string {
	if x != nil && x.PsnId != nil {
		return *x.PsnId
	}
	return ""
}

func (x *GetServiceStatusResponse) GetUnknown_1() int64 {
	if x != nil && x.Unknown_1 != nil {
		return *x.Unknown_1
	}
	return 0
}

func (x *GetServiceStatusResponse) GetAppVersion() int64 {
	if x != nil && x.AppVersion != nil {
		return *x.AppVersion
	}
	return 0
}

var File_Shared_Frpg2RequestMessage_proto protoreflect.FileDescriptor

const file_Shared_Frpg2RequestMessage_proto_rawDesc = "" +
	"\n" +
	" Shared_Frpg2RequestMessage.proto\x12\x1aShared_Frpg2RequestMessage\"e\n" +
	"\x1bRequestQueryLoginServerInfo\x12\x15\n" +
	"\x06psn_id\x18\x01 \x02(\tR\x05psnId\x12\x0e\n" +
	"\x02f2\x18\x02 \x01(\tR\x02f2\x12\x1f\n" +
	"\vapp_version\x18\x03 \x02(\x04R\n" +
	"appVersion\"V\n" +
	"#RequestQueryLoginServerInfoResponse\x12\x12\n" +
	"\x04port\x18\x01 \x02(\x03R\x04port\x12\x1b\n" +
	"\tserver_ip\x18\x02 \x02(\tR\bserverIp\"'\n" +
	"%RequestQueryLoginServerInfoForXboxOne\"2\n" +
	"\x10RequestHandshake\x12\x1e\n" +
	"\vaes_cwc_key\x18\x01 \x02(\fR\taesCwcKey\"\x1a\n" +
	"\x18RequestHandshakeResponse\"w\n" +
	"\x10GetServiceStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x03R\x02id\x12\x15\n" +
	"\x06psn_id\x18\x02 \x02(\tR\x05psnId\x12\x1b\n" +
	"\tunknown_1\x18\x03 \x01(\tR\bunknown1\x12\x1f\n" +
	"\vapp_version\x18\x04 \x02(\x03R\n" +
	"appVersion\"\x1c\n" +
	"\x1aGetServiceStatusForXboxOne\"\x7f\n" +
	"\x18GetServiceStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06psn_id\x18\x02 \x01(\tR\x05psnId\x12\x1b\n" +
	"\tunknown_1\x18\x03 \x01(\x03R\bunknown1\x12\x1f\n" +
	"\vapp_version\x18\x04 \x01(\x03R\n" +
	"appVersionB\xf8\x01\n" +
	"\x1ecom.Shared_Frpg2RequestMessageB\x1eSharedFrpg2RequestMessageProtoH\x01P\x01Z0github.com/sstreight/dso/internal/proto/sharedpb\xa2\x02\x03SXX\xaa\x02\x19SharedFrpg2RequestMessage\xca\x02\x19SharedFrpg2RequestMessage\xe2\x02%SharedFrpg2RequestMessage\\GPBMetadata\xea\x02\x19SharedFrpg2RequestMessage"

var (
	file_Shared_Frpg2RequestMessage_proto_rawDescOnce sync.Once
	file_Shared_Frpg2RequestMessage_proto_rawDescData []byte
)

func file_Shared_Frpg2RequestMessage_proto_rawDescGZIP() []byte {
	file_Shared_Frpg2RequestMessage_proto_rawDescOnce.Do(func() {
		file_Shared_Frpg2RequestMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Shared_Frpg2RequestMessage_proto_rawDesc), len(file_Shared_Frpg2RequestMessage_proto_rawDesc)))
	})
	return file_Shared_Frpg2RequestMessage_proto_rawDescData
}

var file_Shared_Frpg2RequestMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_Shared_Frpg2RequestMessage_proto_goTypes = []any{
	(*RequestQueryLoginServerInfo)(nil),           // 0: Shared_Frpg2RequestMessage.RequestQueryLoginServerInfo
	(*RequestQueryLoginServerInfoResponse)(nil),   // 1: Shared_Frpg2RequestMessage.RequestQueryLoginServerInfoResponse
	(*RequestQueryLoginServerInfoForXboxOne)(nil), // 2: Shared_Frpg2RequestMessage.RequestQueryLoginServerInfoForXboxOne
	(*RequestHandshake)(nil),                      // 3: Shared_Frpg2RequestMessage.RequestHandshake
	(*RequestHandshakeResponse)(nil),              // 4: Shared_Frpg2RequestMessage.RequestHandshakeResponse
	(*GetServiceStatus)(nil),                      // 5: Shared_Frpg2RequestMessage.GetServiceStatus
	(*GetServiceStatusForXboxOne)(nil),            // 6: Shared_Frpg2RequestMessage.GetServiceStatusForXboxOne
	(*GetServiceStatusResponse)(nil),              // 7: Shared_Frpg2RequestMessage.GetServiceStatusResponse
}
var file_Shared_Frpg2RequestMessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Shared_Frpg2RequestMessage_proto_init() }
func file_Shared_Frpg2RequestMessage_proto_init() {
	if File_Shared_Frpg2RequestMessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Shared_Frpg2RequestMessage_proto_rawDesc), len(file_Shared_Frpg2RequestMessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Shared_Frpg2RequestMessage_proto_goTypes,
		DependencyIndexes: file_Shared_Frpg2RequestMessage_proto_depIdxs,
		MessageInfos:      file_Shared_Frpg2RequestMessage_proto_msgTypes,
	}.Build()
	File_Shared_Frpg2RequestMessage_proto = out.File
	file_Shared_Frpg2RequestMessage_proto_goTypes = nil
	file_Shared_Frpg2RequestMessage_proto_depIdxs = nil
}
