//
// Dark Souls 3 - Open Server
// Copyright (C) 2021 Tim Leonard
//
// This program is free software; licensed under the MIT license.
// You should have received a copy of the license along with this program.
// If not, see <https://opensource.org/licenses/MIT>.

// Credit: Parts of this are based on research by: AmirBohd, Radai

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: DS2_Frpg2PlayerData.proto

package ds2datapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlayerLocation   *PlayerLocation        `protobuf:"bytes,1,opt,name=player_location,json=playerLocation" json:"player_location,omitempty"`
	PlayerStatus     *PlayerStatus          `protobuf:"bytes,2,opt,name=player_status,json=playerStatus" json:"player_status,omitempty"`
	ItemUsingInfo    *ItemUsingInfo         `protobuf:"bytes,3,opt,name=item_using_info,json=itemUsingInfo" json:"item_using_info,omitempty"`
	StatsInfo        *StatsInfo             `protobuf:"bytes,4,opt,name=stats_info,json=statsInfo" json:"stats_info,omitempty"`
	Attributes       *LevelStatus           `protobuf:"bytes,5,opt,name=attributes" json:"attributes,omitempty"`
	PhysicalStatus   *PhysicalStatus        `protobuf:"bytes,6,opt,name=physical_status,json=physicalStatus" json:"physical_status,omitempty"`
	WeaponStatus     *WeaponStatus          `protobuf:"bytes,7,opt,name=weapon_status,json=weaponStatus" json:"weapon_status,omitempty"`
	ArmorStatus      *ArmorStatus           `protobuf:"bytes,8,opt,name=armor_status,json=armorStatus" json:"armor_status,omitempty"`
	ServerSideStatus *ServerSideStatus      `protobuf:"bytes,9,opt,name=server_side_status,json=serverSideStatus" json:"server_side_status,omitempty"`
	EquipmentInfo    *EquipmentInfo         `protobuf:"bytes,10,opt,name=equipment_info,json=equipmentInfo" json:"equipment_info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AllStatus) Reset() {
	*x = AllStatus{}
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllStatus) ProtoMessage() {}

func (x *AllStatus) ProtoReflect() protoreflect.Message {
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllStatus.ProtoReflect.Descriptor instead.
func (*AllStatus) Descriptor() ([]byte, []int) {
	return file_DS2_Frpg2PlayerData_proto_rawDescGZIP(), []int{0}
}

func (x *AllStatus) GetPlayerLocation() *PlayerLocation {
	if x != nil {
		return x.PlayerLocation
	}
	return nil
}

func (x *AllStatus) GetPlayerStatus() *PlayerStatus {
	if x != nil {
		return x.PlayerStatus
	}
	return nil
}

func (x *AllStatus) GetItemUsingInfo() *ItemUsingInfo {
	if x != nil {
		return x.ItemUsingInfo
	}
	return nil
}

func (x *AllStatus) GetStatsInfo() *StatsInfo {
	if x != nil {
		return x.StatsInfo
	}
	return nil
}

func (x *AllStatus) GetAttributes() *LevelStatus {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *AllStatus) GetPhysicalStatus() *PhysicalStatus {
	if x != nil {
		return x.PhysicalStatus
	}
	return nil
}

func (x *AllStatus) GetWeaponStatus() *WeaponStatus {
	if x != nil {
		return x.WeaponStatus
	}
	return nil
}

func (x *AllStatus) GetArmorStatus() *ArmorStatus {
	if x != nil {
		return x.ArmorStatus
	}
	return nil
}

func (x *AllStatus) GetServerSideStatus() *ServerSideStatus {
	if x != nil {
		return x.ServerSideStatus
	}
	return nil
}

func (x *AllStatus) GetEquipmentInfo() *EquipmentInfo {
	if x != nil {
		return x.EquipmentInfo
	}
	return nil
}

type ArmorStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrikeDef     *uint32                `protobuf:"varint,1,opt,name=strike_def,json=strikeDef" json:"strike_def,omitempty"`
	SlashDef      *uint32                `protobuf:"varint,2,opt,name=slash_def,json=slashDef" json:"slash_def,omitempty"`
	ThrustDef     *uint32                `protobuf:"varint,3,opt,name=thrust_def,json=thrustDef" json:"thrust_def,omitempty"`
	Poise         *float32               `protobuf:"fixed32,4,opt,name=poise" json:"poise,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArmorStatus) Reset() {
	*x = ArmorStatus{}
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmorStatus) ProtoMessage() {}

func (x *ArmorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmorStatus.ProtoReflect.Descriptor instead.
func (*ArmorStatus) Descriptor() ([]byte, []int) {
	return file_DS2_Frpg2PlayerData_proto_rawDescGZIP(), []int{1}
}

func (x *ArmorStatus) GetStrikeDef() uint32 {
	if x != nil && x.StrikeDef != nil {
		return *x.StrikeDef
	}
	return 0
}

func (x *ArmorStatus) GetSlashDef() uint32 {
	if x != nil && x.SlashDef != nil {
		return *x.SlashDef
	}
	return 0
}

func (x *ArmorStatus) GetThrustDef() uint32 {
	if x != nil && x.ThrustDef != nil {
		return *x.ThrustDef
	}
	return 0
}

func (x *ArmorStatus) GetPoise() float32 {
	if x != nil && x.Poise != nil {
		return *x.Poise
	}
	return 0
}

type DateTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          *uint32                `protobuf:"varint,1,req,name=year" json:"year,omitempty"`
	Month         *uint32                `protobuf:"varint,2,req,name=month" json:"month,omitempty"`
	Day           *uint32                `protobuf:"varint,3,req,name=day" json:"day,omitempty"`
	Hours         *uint32                `protobuf:"varint,4,req,name=hours" json:"hours,omitempty"`
	Minutes       *uint32                `protobuf:"varint,5,req,name=minutes" json:"minutes,omitempty"`
	Seconds       *uint32                `protobuf:"varint,6,req,name=seconds" json:"seconds,omitempty"`
	Tzdiff        *uint32                `protobuf:"varint,7,req,name=tzdiff" json:"tzdiff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateTime) Reset() {
	*x = DateTime{}
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateTime) ProtoMessage() {}

func (x *DateTime) ProtoReflect() protoreflect.Message {
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateTime.ProtoReflect.Descriptor instead.
func (*DateTime) Descriptor() ([]byte, []int) {
	return file_DS2_Frpg2PlayerData_proto_rawDescGZIP(), []int{2}
}

func (x *DateTime) GetYear() uint32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

func (x *DateTime) GetMonth() uint32 {
	if x != nil && x.Month != nil {
		return *x.Month
	}
	return 0
}

func (x *DateTime) GetDay() uint32 {
	if x != nil && x.Day != nil {
		return *x.Day
	}
	return 0
}

func (x *DateTime) GetHours() uint32 {
	if x != nil && x.Hours != nil {
		return *x.Hours
	}
	return 0
}

func (x *DateTime) GetMinutes() uint32 {
	if x != nil && x.Minutes != nil {
		return *x.Minutes
	}
	return 0
}

func (x *DateTime) GetSeconds() uint32 {
	if x != nil && x.Seconds != nil {
		return *x.Seconds
	}
	return 0
}

func (x *DateTime) GetTzdiff() uint32 {
	if x != nil && x.Tzdiff != nil {
		return *x.Tzdiff
	}
	return 0
}

type EquipmentInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WeaponSlots     *uint32                `protobuf:"varint,1,opt,name=weapon_slots,json=weaponSlots" json:"weapon_slots,omitempty"`
	ArmorSlots      *uint32                `protobuf:"varint,2,opt,name=armor_slots,json=armorSlots" json:"armor_slots,omitempty"`
	RingSlots       *uint32                `protobuf:"varint,3,opt,name=ring_slots,json=ringSlots" json:"ring_slots,omitempty"`
	AmmunitionSlots *uint32                `protobuf:"varint,4,opt,name=ammunition_slots,json=ammunitionSlots" json:"ammunition_slots,omitempty"`
	BeltSlots       *uint32                `protobuf:"varint,5,opt,name=belt_slots,json=beltSlots" json:"belt_slots,omitempty"`
	SpellSlots      *uint32                `protobuf:"varint,6,opt,name=spell_slots,json=spellSlots" json:"spell_slots,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EquipmentInfo) Reset() {
	*x = EquipmentInfo{}
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentInfo) ProtoMessage() {}

func (x *EquipmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentInfo.ProtoReflect.Descriptor instead.
func (*EquipmentInfo) Descriptor() ([]byte, []int) {
	return file_DS2_Frpg2PlayerData_proto_rawDescGZIP(), []int{3}
}

func (x *EquipmentInfo) GetWeaponSlots() uint32 {
	if x != nil && x.WeaponSlots != nil {
		return *x.WeaponSlots
	}
	return 0
}

func (x *EquipmentInfo) GetArmorSlots() uint32 {
	if x != nil && x.ArmorSlots != nil {
		return *x.ArmorSlots
	}
	return 0
}

func (x *EquipmentInfo) GetRingSlots() uint32 {
	if x != nil && x.RingSlots != nil {
		return *x.RingSlots
	}
	return 0
}

func (x *EquipmentInfo) GetAmmunitionSlots() uint32 {
	if x != nil && x.AmmunitionSlots != nil {
		return *x.AmmunitionSlots
	}
	return 0
}

func (x *EquipmentInfo) GetBeltSlots() uint32 {
	if x != nil && x.BeltSlots != nil {
		return *x.BeltSlots
	}
	return 0
}

func (x *EquipmentInfo) GetSpellSlots() uint32 {
	if x != nil && x.SpellSlots != nil {
		return *x.SpellSlots
	}
	return 0
}

type ItemUsingInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NamedRingGod      *uint32                `protobuf:"varint,1,opt,name=named_ring_god,json=namedRingGod" json:"named_ring_god,omitempty"`
	UsingDriedFingers *uint32                `protobuf:"varint,2,opt,name=using_dried_fingers,json=usingDriedFingers" json:"using_dried_fingers,omitempty"`
	Unknown_3         *uint32                `protobuf:"varint,3,opt,name=unknown_3,json=unknown3" json:"unknown_3,omitempty"`
	GuardiansSeal     *uint32                `protobuf:"varint,4,opt,name=guardians_seal,json=guardiansSeal" json:"guardians_seal,omitempty"`
	BellKeepersSeal   *uint32                `protobuf:"varint,5,opt,name=bell_keepers_seal,json=bellKeepersSeal" json:"bell_keepers_seal,omitempty"`
	CrestOfTheRat     *uint32                `protobuf:"varint,6,opt,name=crest_of_the_rat,json=crestOfTheRat" json:"crest_of_the_rat,omitempty"`
	Unknown_7         *uint32                `protobuf:"varint,7,opt,name=unknown_7,json=unknown7" json:"unknown_7,omitempty"`
	Unknown_8         *uint32                `protobuf:"varint,8,opt,name=unknown_8,json=unknown8" json:"unknown_8,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ItemUsingInfo) Reset() {
	*x = ItemUsingInfo{}
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemUsingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemUsingInfo) ProtoMessage() {}

func (x *ItemUsingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemUsingInfo.ProtoReflect.Descriptor instead.
func (*ItemUsingInfo) Descriptor() ([]byte, []int) {
	return file_DS2_Frpg2PlayerData_proto_rawDescGZIP(), []int{4}
}

func (x *ItemUsingInfo) GetNamedRingGod() uint32 {
	if x != nil && x.NamedRingGod != nil {
		return *x.NamedRingGod
	}
	return 0
}

func (x *ItemUsingInfo) GetUsingDriedFingers() uint32 {
	if x != nil && x.UsingDriedFingers != nil {
		return *x.UsingDriedFingers
	}
	return 0
}

func (x *ItemUsingInfo) GetUnknown_3() uint32 {
	if x != nil && x.Unknown_3 != nil {
		return *x.Unknown_3
	}
	return 0
}

func (x *ItemUsingInfo) GetGuardiansSeal() uint32 {
	if x != nil && x.GuardiansSeal != nil {
		return *x.GuardiansSeal
	}
	return 0
}

func (x *ItemUsingInfo) GetBellKeepersSeal() uint32 {
	if x != nil && x.BellKeepersSeal != nil {
		return *x.BellKeepersSeal
	}
	return 0
}

func (x *ItemUsingInfo) GetCrestOfTheRat() uint32 {
	if x != nil && x.CrestOfTheRat != nil {
		return *x.CrestOfTheRat
	}
	return 0
}

func (x *ItemUsingInfo) GetUnknown_7() uint32 {
	if x != nil && x.Unknown_7 != nil {
		return *x.Unknown_7
	}
	return 0
}

func (x *ItemUsingInfo) GetUnknown_8() uint32 {
	if x != nil && x.Unknown_8 != nil {
		return *x.Unknown_8
	}
	return 0
}

type LevelStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vigor         *uint32                `protobuf:"varint,1,opt,name=vigor" json:"vigor,omitempty"`
	Endurance     *uint32                `protobuf:"varint,2,opt,name=endurance" json:"endurance,omitempty"`
	Vitality      *uint32                `protobuf:"varint,3,opt,name=vitality" json:"vitality,omitempty"`
	Attunement    *uint32                `protobuf:"varint,4,opt,name=attunement" json:"attunement,omitempty"`
	Strenght      *uint32                `protobuf:"varint,5,opt,name=strenght" json:"strenght,omitempty"`
	Dexterity     *uint32                `protobuf:"varint,6,opt,name=dexterity" json:"dexterity,omitempty"`
	Intelligence  *uint32                `protobuf:"varint,7,opt,name=intelligence" json:"intelligence,omitempty"`
	Faith         *uint32                `protobuf:"varint,8,opt,name=faith" json:"faith,omitempty"`
	Adaptability  *uint32                `protobuf:"varint,9,opt,name=adaptability" json:"adaptability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelStatus) Reset() {
	*x = LevelStatus{}
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelStatus) ProtoMessage() {}

func (x *LevelStatus) ProtoReflect() protoreflect.Message {
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelStatus.ProtoReflect.Descriptor instead.
func (*LevelStatus) Descriptor() ([]byte, []int) {
	return file_DS2_Frpg2PlayerData_proto_rawDescGZIP(), []int{5}
}

func (x *LevelStatus) GetVigor() uint32 {
	if x != nil && x.Vigor != nil {
		return *x.Vigor
	}
	return 0
}

func (x *LevelStatus) GetEndurance() uint32 {
	if x != nil && x.Endurance != nil {
		return *x.Endurance
	}
	return 0
}

func (x *LevelStatus) GetVitality() uint32 {
	if x != nil && x.Vitality != nil {
		return *x.Vitality
	}
	return 0
}

func (x *LevelStatus) GetAttunement() uint32 {
	if x != nil && x.Attunement != nil {
		return *x.Attunement
	}
	return 0
}

func (x *LevelStatus) GetStrenght() uint32 {
	if x != nil && x.Strenght != nil {
		return *x.Strenght
	}
	return 0
}

func (x *LevelStatus) GetDexterity() uint32 {
	if x != nil && x.Dexterity != nil {
		return *x.Dexterity
	}
	return 0
}

func (x *LevelStatus) GetIntelligence() uint32 {
	if x != nil && x.Intelligence != nil {
		return *x.Intelligence
	}
	return 0
}

func (x *LevelStatus) GetFaith() uint32 {
	if x != nil && x.Faith != nil {
		return *x.Faith
	}
	return 0
}

func (x *LevelStatus) GetAdaptability() uint32 {
	if x != nil && x.Adaptability != nil {
		return *x.Adaptability
	}
	return 0
}

type PhantomTypeCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unknown_1     *uint32                `protobuf:"varint,1,opt,name=unknown_1,json=unknown1" json:"unknown_1,omitempty"`
	Unknown_2     *uint32                `protobuf:"varint,2,opt,name=unknown_2,json=unknown2" json:"unknown_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhantomTypeCount) Reset() {
	*x = PhantomTypeCount{}
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhantomTypeCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhantomTypeCount) ProtoMessage() {}

func (x *PhantomTypeCount) ProtoReflect() protoreflect.Message {
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhantomTypeCount.ProtoReflect.Descriptor instead.
func (*PhantomTypeCount) Descriptor() ([]byte, []int) {
	return file_DS2_Frpg2PlayerData_proto_rawDescGZIP(), []int{6}
}

func (x *PhantomTypeCount) GetUnknown_1() uint32 {
	if x != nil && x.Unknown_1 != nil {
		return *x.Unknown_1
	}
	return 0
}

func (x *PhantomTypeCount) GetUnknown_2() uint32 {
	if x != nil && x.Unknown_2 != nil {
		return *x.Unknown_2
	}
	return 0
}

type PhysicalStatus struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Health    *uint32                `protobuf:"varint,1,opt,name=health" json:"health,omitempty"`
	Stamina   *uint32                `protobuf:"varint,2,opt,name=stamina" json:"stamina,omitempty"`
	EquipLoad *float32               `protobuf:"fixed32,3,opt,name=equip_load,json=equipLoad" json:"equip_load,omitempty"`
	// optional uint32 unknown_3 = 3;
	Unknown_4       *uint32  `protobuf:"varint,4,opt,name=unknown_4,json=unknown4" json:"unknown_4,omitempty"`
	Unknown_5       *uint32  `protobuf:"varint,5,opt,name=unknown_5,json=unknown5" json:"unknown_5,omitempty"`
	AttackStrength  *uint32  `protobuf:"varint,6,opt,name=attack_strength,json=attackStrength" json:"attack_strength,omitempty"`
	AttackDexterity *uint32  `protobuf:"varint,7,opt,name=attack_dexterity,json=attackDexterity" json:"attack_dexterity,omitempty"`
	Unknown_8       *uint32  `protobuf:"varint,8,opt,name=unknown_8,json=unknown8" json:"unknown_8,omitempty"`
	Unknown_9       *uint32  `protobuf:"varint,9,opt,name=unknown_9,json=unknown9" json:"unknown_9,omitempty"`
	Unknown_10      *uint32  `protobuf:"varint,10,opt,name=unknown_10,json=unknown10" json:"unknown_10,omitempty"`
	Unknown_11      *uint32  `protobuf:"varint,11,opt,name=unknown_11,json=unknown11" json:"unknown_11,omitempty"`
	Unknown_12      *uint32  `protobuf:"varint,12,opt,name=unknown_12,json=unknown12" json:"unknown_12,omitempty"`
	Unknown_13      *uint32  `protobuf:"varint,13,opt,name=unknown_13,json=unknown13" json:"unknown_13,omitempty"`
	PhysicalDefence *uint32  `protobuf:"varint,14,opt,name=physical_defence,json=physicalDefence" json:"physical_defence,omitempty"`
	Unknown_15      *uint32  `protobuf:"varint,15,opt,name=unknown_15,json=unknown15" json:"unknown_15,omitempty"` // changes with int
	Unknown_16      *uint32  `protobuf:"varint,16,opt,name=unknown_16,json=unknown16" json:"unknown_16,omitempty"` // changes with int
	Unknown_17      *uint32  `protobuf:"varint,17,opt,name=unknown_17,json=unknown17" json:"unknown_17,omitempty"` // changes with faith
	Unknown_18      *uint32  `protobuf:"varint,18,opt,name=unknown_18,json=unknown18" json:"unknown_18,omitempty"` // changes with int
	Unknown_19      *uint32  `protobuf:"varint,19,opt,name=unknown_19,json=unknown19" json:"unknown_19,omitempty"` // changes with adaptability
	Unknown_20      *uint32  `protobuf:"varint,20,opt,name=unknown_20,json=unknown20" json:"unknown_20,omitempty"` // changes with faith
	PetrifyResist   *uint32  `protobuf:"varint,21,opt,name=petrify_resist,json=petrifyResist" json:"petrify_resist,omitempty"`
	CurseResist     *uint32  `protobuf:"varint,22,opt,name=curse_resist,json=curseResist" json:"curse_resist,omitempty"`
	Agility         *uint32  `protobuf:"varint,23,opt,name=agility" json:"agility,omitempty"`
	Poise           *float32 `protobuf:"fixed32,24,opt,name=poise" json:"poise,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PhysicalStatus) Reset() {
	*x = PhysicalStatus{}
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalStatus) ProtoMessage() {}

func (x *PhysicalStatus) ProtoReflect() protoreflect.Message {
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalStatus.ProtoReflect.Descriptor instead.
func (*PhysicalStatus) Descriptor() ([]byte, []int) {
	return file_DS2_Frpg2PlayerData_proto_rawDescGZIP(), []int{7}
}

func (x *PhysicalStatus) GetHealth() uint32 {
	if x != nil && x.Health != nil {
		return *x.Health
	}
	return 0
}

func (x *PhysicalStatus) GetStamina() uint32 {
	if x != nil && x.Stamina != nil {
		return *x.Stamina
	}
	return 0
}

func (x *PhysicalStatus) GetEquipLoad() float32 {
	if x != nil && x.EquipLoad != nil {
		return *x.EquipLoad
	}
	return 0
}

func (x *PhysicalStatus) GetUnknown_4() uint32 {
	if x != nil && x.Unknown_4 != nil {
		return *x.Unknown_4
	}
	return 0
}

func (x *PhysicalStatus) GetUnknown_5() uint32 {
	if x != nil && x.Unknown_5 != nil {
		return *x.Unknown_5
	}
	return 0
}

func (x *PhysicalStatus) GetAttackStrength() uint32 {
	if x != nil && x.AttackStrength != nil {
		return *x.AttackStrength
	}
	return 0
}

func (x *PhysicalStatus) GetAttackDexterity() uint32 {
	if x != nil && x.AttackDexterity != nil {
		return *x.AttackDexterity
	}
	return 0
}

func (x *PhysicalStatus) GetUnknown_8() uint32 {
	if x != nil && x.Unknown_8 != nil {
		return *x.Unknown_8
	}
	return 0
}

func (x *PhysicalStatus) GetUnknown_9() uint32 {
	if x != nil && x.Unknown_9 != nil {
		return *x.Unknown_9
	}
	return 0
}

func (x *PhysicalStatus) GetUnknown_10() uint32 {
	if x != nil && x.Unknown_10 != nil {
		return *x.Unknown_10
	}
	return 0
}

func (x *PhysicalStatus) GetUnknown_11() uint32 {
	if x != nil && x.Unknown_11 != nil {
		return *x.Unknown_11
	}
	return 0
}

func (x *PhysicalStatus) GetUnknown_12() uint32 {
	if x != nil && x.Unknown_12 != nil {
		return *x.Unknown_12
	}
	return 0
}

func (x *PhysicalStatus) GetUnknown_13() uint32 {
	if x != nil && x.Unknown_13 != nil {
		return *x.Unknown_13
	}
	return 0
}

func (x *PhysicalStatus) GetPhysicalDefence() uint32 {
	if x != nil && x.PhysicalDefence != nil {
		return *x.PhysicalDefence
	}
	return 0
}

func (x *PhysicalStatus) GetUnknown_15() uint32 {
	if x != nil && x.Unknown_15 != nil {
		return *x.Unknown_15
	}
	return 0
}

func (x *PhysicalStatus) GetUnknown_16() uint32 {
	if x != nil && x.Unknown_16 != nil {
		return *x.Unknown_16
	}
	return 0
}

func (x *PhysicalStatus) GetUnknown_17() uint32 {
	if x != nil && x.Unknown_17 != nil {
		return *x.Unknown_17
	}
	return 0
}

func (x *PhysicalStatus) GetUnknown_18() uint32 {
	if x != nil && x.Unknown_18 != nil {
		return *x.Unknown_18
	}
	return 0
}

func (x *PhysicalStatus) GetUnknown_19() uint32 {
	if x != nil && x.Unknown_19 != nil {
		return *x.Unknown_19
	}
	return 0
}

func (x *PhysicalStatus) GetUnknown_20() uint32 {
	if x != nil && x.Unknown_20 != nil {
		return *x.Unknown_20
	}
	return 0
}

func (x *PhysicalStatus) GetPetrifyResist() uint32 {
	if x != nil && x.PetrifyResist != nil {
		return *x.PetrifyResist
	}
	return 0
}

func (x *PhysicalStatus) GetCurseResist() uint32 {
	if x != nil && x.CurseResist != nil {
		return *x.CurseResist
	}
	return 0
}

func (x *PhysicalStatus) GetAgility() uint32 {
	if x != nil && x.Agility != nil {
		return *x.Agility
	}
	return 0
}

func (x *PhysicalStatus) GetPoise() float32 {
	if x != nil && x.Poise != nil {
		return *x.Poise
	}
	return 0
}

type PlayerLocation struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	OnlineAreaId         *uint32                `protobuf:"varint,1,opt,name=online_area_id,json=onlineAreaId" json:"online_area_id,omitempty"`
	CellId               *uint32                `protobuf:"varint,2,opt,name=cell_id,json=cellId" json:"cell_id,omitempty"`                                               // 1074321607, 3225573558, 1078414675,
	OnlineActivityAreaId *uint32                `protobuf:"varint,3,opt,name=online_activity_area_id,json=onlineActivityAreaId" json:"online_activity_area_id,omitempty"` // 0, 101640, 103130, 103110, 103120,
	Position             *Vector                `protobuf:"bytes,4,opt,name=position" json:"position,omitempty"`
	Unknown_5            *float32               `protobuf:"fixed32,5,opt,name=unknown_5,json=unknown5" json:"unknown_5,omitempty"` // 1074321607, 3225573558, 1078414675
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PlayerLocation) Reset() {
	*x = PlayerLocation{}
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLocation) ProtoMessage() {}

func (x *PlayerLocation) ProtoReflect() protoreflect.Message {
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLocation.ProtoReflect.Descriptor instead.
func (*PlayerLocation) Descriptor() ([]byte, []int) {
	return file_DS2_Frpg2PlayerData_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerLocation) GetOnlineAreaId() uint32 {
	if x != nil && x.OnlineAreaId != nil {
		return *x.OnlineAreaId
	}
	return 0
}

func (x *PlayerLocation) GetCellId() uint32 {
	if x != nil && x.CellId != nil {
		return *x.CellId
	}
	return 0
}

func (x *PlayerLocation) GetOnlineActivityAreaId() uint32 {
	if x != nil && x.OnlineActivityAreaId != nil {
		return *x.OnlineActivityAreaId
	}
	return 0
}

func (x *PlayerLocation) GetPosition() *Vector {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerLocation) GetUnknown_5() float32 {
	if x != nil && x.Unknown_5 != nil {
		return *x.Unknown_5
	}
	return 0
}

type PlayerStatus_PhantomLeaveAt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unknown_1     *uint32                `protobuf:"varint,1,opt,name=unknown_1,json=unknown1" json:"unknown_1,omitempty"`
	Datetime      *DateTime              `protobuf:"bytes,2,opt,name=datetime" json:"datetime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerStatus_PhantomLeaveAt) Reset() {
	*x = PlayerStatus_PhantomLeaveAt{}
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStatus_PhantomLeaveAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStatus_PhantomLeaveAt) ProtoMessage() {}

func (x *PlayerStatus_PhantomLeaveAt) ProtoReflect() protoreflect.Message {
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStatus_PhantomLeaveAt.ProtoReflect.Descriptor instead.
func (*PlayerStatus_PhantomLeaveAt) Descriptor() ([]byte, []int) {
	return file_DS2_Frpg2PlayerData_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerStatus_PhantomLeaveAt) GetUnknown_1() uint32 {
	if x != nil && x.Unknown_1 != nil {
		return *x.Unknown_1
	}
	return 0
}

func (x *PlayerStatus_PhantomLeaveAt) GetDatetime() *DateTime {
	if x != nil {
		return x.Datetime
	}
	return nil
}

type PlayerStatus struct {
	state                  protoimpl.MessageState       `protogen:"open.v1"`
	Name                   *string                      `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Archetype              *uint32                      `protobuf:"varint,2,opt,name=archetype" json:"archetype,omitempty"`
	Covenant               *uint32                      `protobuf:"varint,3,opt,name=covenant" json:"covenant,omitempty"`
	Unknown_4              *uint32                      `protobuf:"varint,4,opt,name=unknown_4,json=unknown4" json:"unknown_4,omitempty"` // 1, 0
	Unknown_5              *uint32                      `protobuf:"varint,5,opt,name=unknown_5,json=unknown5" json:"unknown_5,omitempty"` // 0, 1, 2
	Unknown_6              *uint32                      `protobuf:"varint,6,opt,name=unknown_6,json=unknown6" json:"unknown_6,omitempty"` // 0
	SittingAtBonfire       *uint32                      `protobuf:"varint,7,opt,name=sitting_at_bonfire,json=sittingAtBonfire" json:"sitting_at_bonfire,omitempty"`
	PhantomLeaveAt         *PlayerStatus_PhantomLeaveAt `protobuf:"bytes,8,opt,name=phantom_leave_at,json=phantomLeaveAt" json:"phantom_leave_at,omitempty"`
	DisableCrossRegionPlay *uint32                      `protobuf:"varint,9,opt,name=disable_cross_region_play,json=disableCrossRegionPlay" json:"disable_cross_region_play,omitempty"`
	CharacterId            *uint32                      `protobuf:"varint,10,opt,name=character_id,json=characterId" json:"character_id,omitempty"`
	HumanEffigyBurnt       *uint32                      `protobuf:"varint,11,opt,name=human_effigy_burnt,json=humanEffigyBurnt" json:"human_effigy_burnt,omitempty"`
	PlayedAreas            []uint32                     `protobuf:"varint,12,rep,name=played_areas,json=playedAreas" json:"played_areas,omitempty"`
	Unknown_13             *uint32                      `protobuf:"varint,13,opt,name=unknown_13,json=unknown13" json:"unknown_13,omitempty"`
	Unknown_14             *uint32                      `protobuf:"varint,14,opt,name=unknown_14,json=unknown14" json:"unknown_14,omitempty"`
	SoulLevel              *uint32                      `protobuf:"varint,15,opt,name=soul_level,json=soulLevel" json:"soul_level,omitempty"`
	Unknown_16             *uint32                      `protobuf:"varint,16,opt,name=unknown_16,json=unknown16" json:"unknown_16,omitempty"`
	Unknown_17             *uint32                      `protobuf:"varint,17,opt,name=unknown_17,json=unknown17" json:"unknown_17,omitempty"`
	PlayTimeSeconds        *uint32                      `protobuf:"varint,18,opt,name=play_time_seconds,json=playTimeSeconds" json:"play_time_seconds,omitempty"`
	SoulMemory             *uint32                      `protobuf:"varint,19,opt,name=soul_memory,json=soulMemory" json:"soul_memory,omitempty"`
	Unknown_20             *uint32                      `protobuf:"varint,20,opt,name=unknown_20,json=unknown20" json:"unknown_20,omitempty"`
	Unknown_21             *string                      `protobuf:"bytes,21,opt,name=unknown_21,json=unknown21" json:"unknown_21,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PlayerStatus) Reset() {
	*x = PlayerStatus{}
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStatus) ProtoMessage() {}

func (x *PlayerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStatus.ProtoReflect.Descriptor instead.
func (*PlayerStatus) Descriptor() ([]byte, []int) {
	return file_DS2_Frpg2PlayerData_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerStatus) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PlayerStatus) GetArchetype() uint32 {
	if x != nil && x.Archetype != nil {
		return *x.Archetype
	}
	return 0
}

func (x *PlayerStatus) GetCovenant() uint32 {
	if x != nil && x.Covenant != nil {
		return *x.Covenant
	}
	return 0
}

func (x *PlayerStatus) GetUnknown_4() uint32 {
	if x != nil && x.Unknown_4 != nil {
		return *x.Unknown_4
	}
	return 0
}

func (x *PlayerStatus) GetUnknown_5() uint32 {
	if x != nil && x.Unknown_5 != nil {
		return *x.Unknown_5
	}
	return 0
}

func (x *PlayerStatus) GetUnknown_6() uint32 {
	if x != nil && x.Unknown_6 != nil {
		return *x.Unknown_6
	}
	return 0
}

func (x *PlayerStatus) GetSittingAtBonfire() uint32 {
	if x != nil && x.SittingAtBonfire != nil {
		return *x.SittingAtBonfire
	}
	return 0
}

func (x *PlayerStatus) GetPhantomLeaveAt() *PlayerStatus_PhantomLeaveAt {
	if x != nil {
		return x.PhantomLeaveAt
	}
	return nil
}

func (x *PlayerStatus) GetDisableCrossRegionPlay() uint32 {
	if x != nil && x.DisableCrossRegionPlay != nil {
		return *x.DisableCrossRegionPlay
	}
	return 0
}

func (x *PlayerStatus) GetCharacterId() uint32 {
	if x != nil && x.CharacterId != nil {
		return *x.CharacterId
	}
	return 0
}

func (x *PlayerStatus) GetHumanEffigyBurnt() uint32 {
	if x != nil && x.HumanEffigyBurnt != nil {
		return *x.HumanEffigyBurnt
	}
	return 0
}

func (x *PlayerStatus) GetPlayedAreas() []uint32 {
	if x != nil {
		return x.PlayedAreas
	}
	return nil
}

func (x *PlayerStatus) GetUnknown_13() uint32 {
	if x != nil && x.Unknown_13 != nil {
		return *x.Unknown_13
	}
	return 0
}

func (x *PlayerStatus) GetUnknown_14() uint32 {
	if x != nil && x.Unknown_14 != nil {
		return *x.Unknown_14
	}
	return 0
}

func (x *PlayerStatus) GetSoulLevel() uint32 {
	if x != nil && x.SoulLevel != nil {
		return *x.SoulLevel
	}
	return 0
}

func (x *PlayerStatus) GetUnknown_16() uint32 {
	if x != nil && x.Unknown_16 != nil {
		return *x.Unknown_16
	}
	return 0
}

func (x *PlayerStatus) GetUnknown_17() uint32 {
	if x != nil && x.Unknown_17 != nil {
		return *x.Unknown_17
	}
	return 0
}

func (x *PlayerStatus) GetPlayTimeSeconds() uint32 {
	if x != nil && x.PlayTimeSeconds != nil {
		return *x.PlayTimeSeconds
	}
	return 0
}

func (x *PlayerStatus) GetSoulMemory() uint32 {
	if x != nil && x.SoulMemory != nil {
		return *x.SoulMemory
	}
	return 0
}

func (x *PlayerStatus) GetUnknown_20() uint32 {
	if x != nil && x.Unknown_20 != nil {
		return *x.Unknown_20
	}
	return 0
}

func (x *PlayerStatus) GetUnknown_21() string {
	if x != nil && x.Unknown_21 != nil {
		return *x.Unknown_21
	}
	return ""
}

type ServerSideStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unknown_1     *uint32                `protobuf:"varint,1,opt,name=unknown_1,json=unknown1" json:"unknown_1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerSideStatus) Reset() {
	*x = ServerSideStatus{}
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerSideStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSideStatus) ProtoMessage() {}

func (x *ServerSideStatus) ProtoReflect() protoreflect.Message {
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSideStatus.ProtoReflect.Descriptor instead.
func (*ServerSideStatus) Descriptor() ([]byte, []int) {
	return file_DS2_Frpg2PlayerData_proto_rawDescGZIP(), []int{11}
}

func (x *ServerSideStatus) GetUnknown_1() uint32 {
	if x != nil && x.Unknown_1 != nil {
		return *x.Unknown_1
	}
	return 0
}

type StatsInfo_BonfireLevels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BonfireId     *uint32                `protobuf:"varint,1,opt,name=bonfire_id,json=bonfireId" json:"bonfire_id,omitempty"`
	BonfireLevel  *uint32                `protobuf:"varint,2,opt,name=bonfire_level,json=bonfireLevel" json:"bonfire_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsInfo_BonfireLevels) Reset() {
	*x = StatsInfo_BonfireLevels{}
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsInfo_BonfireLevels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsInfo_BonfireLevels) ProtoMessage() {}

func (x *StatsInfo_BonfireLevels) ProtoReflect() protoreflect.Message {
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsInfo_BonfireLevels.ProtoReflect.Descriptor instead.
func (*StatsInfo_BonfireLevels) Descriptor() ([]byte, []int) {
	return file_DS2_Frpg2PlayerData_proto_rawDescGZIP(), []int{12}
}

func (x *StatsInfo_BonfireLevels) GetBonfireId() uint32 {
	if x != nil && x.BonfireId != nil {
		return *x.BonfireId
	}
	return 0
}

func (x *StatsInfo_BonfireLevels) GetBonfireLevel() uint32 {
	if x != nil && x.BonfireLevel != nil {
		return *x.BonfireLevel
	}
	return 0
}

type StatsInfo struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	Unknown_1          *uint32                    `protobuf:"varint,1,opt,name=unknown_1,json=unknown1" json:"unknown_1,omitempty"`
	Unknown_2          *uint32                    `protobuf:"varint,2,opt,name=unknown_2,json=unknown2" json:"unknown_2,omitempty"`
	SinnerPoints       *uint32                    `protobuf:"varint,3,opt,name=sinner_points,json=sinnerPoints" json:"sinner_points,omitempty"`
	BonfireLevels      []*StatsInfo_BonfireLevels `protobuf:"bytes,4,rep,name=bonfire_levels,json=bonfireLevels" json:"bonfire_levels,omitempty"`
	Unknown_5          *uint32                    `protobuf:"varint,5,opt,name=unknown_5,json=unknown5" json:"unknown_5,omitempty"`
	PhantomTypeCount_6 []*PhantomTypeCount        `protobuf:"bytes,6,rep,name=phantom_type_count_6,json=phantomTypeCount6" json:"phantom_type_count_6,omitempty"`
	PhantomTypeCount_7 []*PhantomTypeCount        `protobuf:"bytes,7,rep,name=phantom_type_count_7,json=phantomTypeCount7" json:"phantom_type_count_7,omitempty"`
	PhantomTypeCount_8 []*PhantomTypeCount        `protobuf:"bytes,8,rep,name=phantom_type_count_8,json=phantomTypeCount8" json:"phantom_type_count_8,omitempty"`
	PhantomTypeCount_9 []*PhantomTypeCount        `protobuf:"bytes,9,rep,name=phantom_type_count_9,json=phantomTypeCount9" json:"phantom_type_count_9,omitempty"`
	Unknown_10         *uint32                    `protobuf:"varint,10,opt,name=unknown_10,json=unknown10" json:"unknown_10,omitempty"`
	Unknown_11         []uint32                   `protobuf:"varint,11,rep,name=unknown_11,json=unknown11" json:"unknown_11,omitempty"`
	Unknown_12         *uint32                    `protobuf:"varint,12,opt,name=unknown_12,json=unknown12" json:"unknown_12,omitempty"`
	Unknown_13         *uint32                    `protobuf:"varint,13,opt,name=unknown_13,json=unknown13" json:"unknown_13,omitempty"`
	Unknown_14         *uint32                    `protobuf:"varint,14,opt,name=unknown_14,json=unknown14" json:"unknown_14,omitempty"`
	Unknown_15         *uint32                    `protobuf:"varint,15,opt,name=unknown_15,json=unknown15" json:"unknown_15,omitempty"`
	Unknown_16         *uint32                    `protobuf:"varint,16,opt,name=unknown_16,json=unknown16" json:"unknown_16,omitempty"`
	Datetime           *DateTime                  `protobuf:"bytes,17,opt,name=datetime" json:"datetime,omitempty"`
	Unknown_18         *uint32                    `protobuf:"varint,18,opt,name=unknown_18,json=unknown18" json:"unknown_18,omitempty"`
	UnlockedBonfires   []uint32                   `protobuf:"varint,19,rep,name=unlocked_bonfires,json=unlockedBonfires" json:"unlocked_bonfires,omitempty"`
	Unknown_20         *uint32                    `protobuf:"varint,20,opt,name=unknown_20,json=unknown20" json:"unknown_20,omitempty"`
	Unknown_21         []uint32                   `protobuf:"varint,21,rep,name=unknown_21,json=unknown21" json:"unknown_21,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatsInfo) Reset() {
	*x = StatsInfo{}
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsInfo) ProtoMessage() {}

func (x *StatsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsInfo.ProtoReflect.Descriptor instead.
func (*StatsInfo) Descriptor() ([]byte, []int) {
	return file_DS2_Frpg2PlayerData_proto_rawDescGZIP(), []int{13}
}

func (x *StatsInfo) GetUnknown_1() uint32 {
	if x != nil && x.Unknown_1 != nil {
		return *x.Unknown_1
	}
	return 0
}

func (x *StatsInfo) GetUnknown_2() uint32 {
	if x != nil && x.Unknown_2 != nil {
		return *x.Unknown_2
	}
	return 0
}

func (x *StatsInfo) GetSinnerPoints() uint32 {
	if x != nil && x.SinnerPoints != nil {
		return *x.SinnerPoints
	}
	return 0
}

func (x *StatsInfo) GetBonfireLevels() []*StatsInfo_BonfireLevels {
	if x != nil {
		return x.BonfireLevels
	}
	return nil
}

func (x *StatsInfo) GetUnknown_5() uint32 {
	if x != nil && x.Unknown_5 != nil {
		return *x.Unknown_5
	}
	return 0
}

func (x *StatsInfo) GetPhantomTypeCount_6() []*PhantomTypeCount {
	if x != nil {
		return x.PhantomTypeCount_6
	}
	return nil
}

func (x *StatsInfo) GetPhantomTypeCount_7() []*PhantomTypeCount {
	if x != nil {
		return x.PhantomTypeCount_7
	}
	return nil
}

func (x *StatsInfo) GetPhantomTypeCount_8() []*PhantomTypeCount {
	if x != nil {
		return x.PhantomTypeCount_8
	}
	return nil
}

func (x *StatsInfo) GetPhantomTypeCount_9() []*PhantomTypeCount {
	if x != nil {
		return x.PhantomTypeCount_9
	}
	return nil
}

func (x *StatsInfo) GetUnknown_10() uint32 {
	if x != nil && x.Unknown_10 != nil {
		return *x.Unknown_10
	}
	return 0
}

func (x *StatsInfo) GetUnknown_11() []uint32 {
	if x != nil {
		return x.Unknown_11
	}
	return nil
}

func (x *StatsInfo) GetUnknown_12() uint32 {
	if x != nil && x.Unknown_12 != nil {
		return *x.Unknown_12
	}
	return 0
}

func (x *StatsInfo) GetUnknown_13() uint32 {
	if x != nil && x.Unknown_13 != nil {
		return *x.Unknown_13
	}
	return 0
}

func (x *StatsInfo) GetUnknown_14() uint32 {
	if x != nil && x.Unknown_14 != nil {
		return *x.Unknown_14
	}
	return 0
}

func (x *StatsInfo) GetUnknown_15() uint32 {
	if x != nil && x.Unknown_15 != nil {
		return *x.Unknown_15
	}
	return 0
}

func (x *StatsInfo) GetUnknown_16() uint32 {
	if x != nil && x.Unknown_16 != nil {
		return *x.Unknown_16
	}
	return 0
}

func (x *StatsInfo) GetDatetime() *DateTime {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *StatsInfo) GetUnknown_18() uint32 {
	if x != nil && x.Unknown_18 != nil {
		return *x.Unknown_18
	}
	return 0
}

func (x *StatsInfo) GetUnlockedBonfires() []uint32 {
	if x != nil {
		return x.UnlockedBonfires
	}
	return nil
}

func (x *StatsInfo) GetUnknown_20() uint32 {
	if x != nil && x.Unknown_20 != nil {
		return *x.Unknown_20
	}
	return 0
}

func (x *StatsInfo) GetUnknown_21() []uint32 {
	if x != nil {
		return x.Unknown_21
	}
	return nil
}

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *float32               `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y             *float32               `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	Z             *float32               `protobuf:"fixed32,3,req,name=z" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_DS2_Frpg2PlayerData_proto_rawDescGZIP(), []int{14}
}

func (x *Vector) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Vector) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *Vector) GetZ() float32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

type WeaponStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeftAr_1      *uint32                `protobuf:"varint,1,opt,name=left_ar_1,json=leftAr1" json:"left_ar_1,omitempty"`
	LeftAr_2      *uint32                `protobuf:"varint,2,opt,name=left_ar_2,json=leftAr2" json:"left_ar_2,omitempty"`
	LeftAr_3      *uint32                `protobuf:"varint,3,opt,name=left_ar_3,json=leftAr3" json:"left_ar_3,omitempty"`
	RightAr_1     *uint32                `protobuf:"varint,4,opt,name=right_ar_1,json=rightAr1" json:"right_ar_1,omitempty"`
	RightAr_2     *uint32                `protobuf:"varint,5,opt,name=right_ar_2,json=rightAr2" json:"right_ar_2,omitempty"`
	RightAr_3     *uint32                `protobuf:"varint,6,opt,name=right_ar_3,json=rightAr3" json:"right_ar_3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeaponStatus) Reset() {
	*x = WeaponStatus{}
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeaponStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeaponStatus) ProtoMessage() {}

func (x *WeaponStatus) ProtoReflect() protoreflect.Message {
	mi := &file_DS2_Frpg2PlayerData_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeaponStatus.ProtoReflect.Descriptor instead.
func (*WeaponStatus) Descriptor() ([]byte, []int) {
	return file_DS2_Frpg2PlayerData_proto_rawDescGZIP(), []int{15}
}

func (x *WeaponStatus) GetLeftAr_1() uint32 {
	if x != nil && x.LeftAr_1 != nil {
		return *x.LeftAr_1
	}
	return 0
}

func (x *WeaponStatus) GetLeftAr_2() uint32 {
	if x != nil && x.LeftAr_2 != nil {
		return *x.LeftAr_2
	}
	return 0
}

func (x *WeaponStatus) GetLeftAr_3() uint32 {
	if x != nil && x.LeftAr_3 != nil {
		return *x.LeftAr_3
	}
	return 0
}

func (x *WeaponStatus) GetRightAr_1() uint32 {
	if x != nil && x.RightAr_1 != nil {
		return *x.RightAr_1
	}
	return 0
}

func (x *WeaponStatus) GetRightAr_2() uint32 {
	if x != nil && x.RightAr_2 != nil {
		return *x.RightAr_2
	}
	return 0
}

func (x *WeaponStatus) GetRightAr_3() uint32 {
	if x != nil && x.RightAr_3 != nil {
		return *x.RightAr_3
	}
	return 0
}

var File_DS2_Frpg2PlayerData_proto protoreflect.FileDescriptor

const file_DS2_Frpg2PlayerData_proto_rawDesc = "" +
	"\n" +
	"\x19DS2_Frpg2PlayerData.proto\x12\x13DS2_Frpg2PlayerData\"\xe9\x05\n" +
	"\tAllStatus\x12L\n" +
	"\x0fplayer_location\x18\x01 \x01(\v2#.DS2_Frpg2PlayerData.PlayerLocationR\x0eplayerLocation\x12F\n" +
	"\rplayer_status\x18\x02 \x01(\v2!.DS2_Frpg2PlayerData.PlayerStatusR\fplayerStatus\x12J\n" +
	"\x0fitem_using_info\x18\x03 \x01(\v2\".DS2_Frpg2PlayerData.ItemUsingInfoR\ritemUsingInfo\x12=\n" +
	"\n" +
	"stats_info\x18\x04 \x01(\v2\x1e.DS2_Frpg2PlayerData.StatsInfoR\tstatsInfo\x12@\n" +
	"\n" +
	"attributes\x18\x05 \x01(\v2 .DS2_Frpg2PlayerData.LevelStatusR\n" +
	"attributes\x12L\n" +
	"\x0fphysical_status\x18\x06 \x01(\v2#.DS2_Frpg2PlayerData.PhysicalStatusR\x0ephysicalStatus\x12F\n" +
	"\rweapon_status\x18\a \x01(\v2!.DS2_Frpg2PlayerData.WeaponStatusR\fweaponStatus\x12C\n" +
	"\farmor_status\x18\b \x01(\v2 .DS2_Frpg2PlayerData.ArmorStatusR\varmorStatus\x12S\n" +
	"\x12server_side_status\x18\t \x01(\v2%.DS2_Frpg2PlayerData.ServerSideStatusR\x10serverSideStatus\x12I\n" +
	"\x0eequipment_info\x18\n" +
	" \x01(\v2\".DS2_Frpg2PlayerData.EquipmentInfoR\requipmentInfo\"~\n" +
	"\vArmorStatus\x12\x1d\n" +
	"\n" +
	"strike_def\x18\x01 \x01(\rR\tstrikeDef\x12\x1b\n" +
	"\tslash_def\x18\x02 \x01(\rR\bslashDef\x12\x1d\n" +
	"\n" +
	"thrust_def\x18\x03 \x01(\rR\tthrustDef\x12\x14\n" +
	"\x05poise\x18\x04 \x01(\x02R\x05poise\"\xa8\x01\n" +
	"\bDateTime\x12\x12\n" +
	"\x04year\x18\x01 \x02(\rR\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x02(\rR\x05month\x12\x10\n" +
	"\x03day\x18\x03 \x02(\rR\x03day\x12\x14\n" +
	"\x05hours\x18\x04 \x02(\rR\x05hours\x12\x18\n" +
	"\aminutes\x18\x05 \x02(\rR\aminutes\x12\x18\n" +
	"\aseconds\x18\x06 \x02(\rR\aseconds\x12\x16\n" +
	"\x06tzdiff\x18\a \x02(\rR\x06tzdiff\"\xdd\x01\n" +
	"\rEquipmentInfo\x12!\n" +
	"\fweapon_slots\x18\x01 \x01(\rR\vweaponSlots\x12\x1f\n" +
	"\varmor_slots\x18\x02 \x01(\rR\n" +
	"armorSlots\x12\x1d\n" +
	"\n" +
	"ring_slots\x18\x03 \x01(\rR\tringSlots\x12)\n" +
	"\x10ammunition_slots\x18\x04 \x01(\rR\x0fammunitionSlots\x12\x1d\n" +
	"\n" +
	"belt_slots\x18\x05 \x01(\rR\tbeltSlots\x12\x1f\n" +
	"\vspell_slots\x18\x06 \x01(\rR\n" +
	"spellSlots\"\xb8\x02\n" +
	"\rItemUsingInfo\x12$\n" +
	"\x0enamed_ring_god\x18\x01 \x01(\rR\fnamedRingGod\x12.\n" +
	"\x13using_dried_fingers\x18\x02 \x01(\rR\x11usingDriedFingers\x12\x1b\n" +
	"\tunknown_3\x18\x03 \x01(\rR\bunknown3\x12%\n" +
	"\x0eguardians_seal\x18\x04 \x01(\rR\rguardiansSeal\x12*\n" +
	"\x11bell_keepers_seal\x18\x05 \x01(\rR\x0fbellKeepersSeal\x12'\n" +
	"\x10crest_of_the_rat\x18\x06 \x01(\rR\rcrestOfTheRat\x12\x1b\n" +
	"\tunknown_7\x18\a \x01(\rR\bunknown7\x12\x1b\n" +
	"\tunknown_8\x18\b \x01(\rR\bunknown8\"\x95\x02\n" +
	"\vLevelStatus\x12\x14\n" +
	"\x05vigor\x18\x01 \x01(\rR\x05vigor\x12\x1c\n" +
	"\tendurance\x18\x02 \x01(\rR\tendurance\x12\x1a\n" +
	"\bvitality\x18\x03 \x01(\rR\bvitality\x12\x1e\n" +
	"\n" +
	"attunement\x18\x04 \x01(\rR\n" +
	"attunement\x12\x1a\n" +
	"\bstrenght\x18\x05 \x01(\rR\bstrenght\x12\x1c\n" +
	"\tdexterity\x18\x06 \x01(\rR\tdexterity\x12\"\n" +
	"\fintelligence\x18\a \x01(\rR\fintelligence\x12\x14\n" +
	"\x05faith\x18\b \x01(\rR\x05faith\x12\"\n" +
	"\fadaptability\x18\t \x01(\rR\fadaptability\"L\n" +
	"\x10PhantomTypeCount\x12\x1b\n" +
	"\tunknown_1\x18\x01 \x01(\rR\bunknown1\x12\x1b\n" +
	"\tunknown_2\x18\x02 \x01(\rR\bunknown2\"\x84\x06\n" +
	"\x0ePhysicalStatus\x12\x16\n" +
	"\x06health\x18\x01 \x01(\rR\x06health\x12\x18\n" +
	"\astamina\x18\x02 \x01(\rR\astamina\x12\x1d\n" +
	"\n" +
	"equip_load\x18\x03 \x01(\x02R\tequipLoad\x12\x1b\n" +
	"\tunknown_4\x18\x04 \x01(\rR\bunknown4\x12\x1b\n" +
	"\tunknown_5\x18\x05 \x01(\rR\bunknown5\x12'\n" +
	"\x0fattack_strength\x18\x06 \x01(\rR\x0eattackStrength\x12)\n" +
	"\x10attack_dexterity\x18\a \x01(\rR\x0fattackDexterity\x12\x1b\n" +
	"\tunknown_8\x18\b \x01(\rR\bunknown8\x12\x1b\n" +
	"\tunknown_9\x18\t \x01(\rR\bunknown9\x12\x1d\n" +
	"\n" +
	"unknown_10\x18\n" +
	" \x01(\rR\tunknown10\x12\x1d\n" +
	"\n" +
	"unknown_11\x18\v \x01(\rR\tunknown11\x12\x1d\n" +
	"\n" +
	"unknown_12\x18\f \x01(\rR\tunknown12\x12\x1d\n" +
	"\n" +
	"unknown_13\x18\r \x01(\rR\tunknown13\x12)\n" +
	"\x10physical_defence\x18\x0e \x01(\rR\x0fphysicalDefence\x12\x1d\n" +
	"\n" +
	"unknown_15\x18\x0f \x01(\rR\tunknown15\x12\x1d\n" +
	"\n" +
	"unknown_16\x18\x10 \x01(\rR\tunknown16\x12\x1d\n" +
	"\n" +
	"unknown_17\x18\x11 \x01(\rR\tunknown17\x12\x1d\n" +
	"\n" +
	"unknown_18\x18\x12 \x01(\rR\tunknown18\x12\x1d\n" +
	"\n" +
	"unknown_19\x18\x13 \x01(\rR\tunknown19\x12\x1d\n" +
	"\n" +
	"unknown_20\x18\x14 \x01(\rR\tunknown20\x12%\n" +
	"\x0epetrify_resist\x18\x15 \x01(\rR\rpetrifyResist\x12!\n" +
	"\fcurse_resist\x18\x16 \x01(\rR\vcurseResist\x12\x18\n" +
	"\aagility\x18\x17 \x01(\rR\aagility\x12\x14\n" +
	"\x05poise\x18\x18 \x01(\x02R\x05poise\"\xdc\x01\n" +
	"\x0ePlayerLocation\x12$\n" +
	"\x0eonline_area_id\x18\x01 \x01(\rR\fonlineAreaId\x12\x17\n" +
	"\acell_id\x18\x02 \x01(\rR\x06cellId\x125\n" +
	"\x17online_activity_area_id\x18\x03 \x01(\rR\x14onlineActivityAreaId\x127\n" +
	"\bposition\x18\x04 \x01(\v2\x1b.DS2_Frpg2PlayerData.VectorR\bposition\x12\x1b\n" +
	"\tunknown_5\x18\x05 \x01(\x02R\bunknown5\"w\n" +
	"\x1dPlayerStatus_Phantom_leave_at\x12\x1b\n" +
	"\tunknown_1\x18\x01 \x01(\rR\bunknown1\x129\n" +
	"\bdatetime\x18\x02 \x01(\v2\x1d.DS2_Frpg2PlayerData.DateTimeR\bdatetime\"\x94\x06\n" +
	"\fPlayerStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tarchetype\x18\x02 \x01(\rR\tarchetype\x12\x1a\n" +
	"\bcovenant\x18\x03 \x01(\rR\bcovenant\x12\x1b\n" +
	"\tunknown_4\x18\x04 \x01(\rR\bunknown4\x12\x1b\n" +
	"\tunknown_5\x18\x05 \x01(\rR\bunknown5\x12\x1b\n" +
	"\tunknown_6\x18\x06 \x01(\rR\bunknown6\x12,\n" +
	"\x12sitting_at_bonfire\x18\a \x01(\rR\x10sittingAtBonfire\x12\\\n" +
	"\x10phantom_leave_at\x18\b \x01(\v22.DS2_Frpg2PlayerData.PlayerStatus_Phantom_leave_atR\x0ephantomLeaveAt\x129\n" +
	"\x19disable_cross_region_play\x18\t \x01(\rR\x16disableCrossRegionPlay\x12!\n" +
	"\fcharacter_id\x18\n" +
	" \x01(\rR\vcharacterId\x12,\n" +
	"\x12human_effigy_burnt\x18\v \x01(\rR\x10humanEffigyBurnt\x12!\n" +
	"\fplayed_areas\x18\f \x03(\rR\vplayedAreas\x12\x1d\n" +
	"\n" +
	"unknown_13\x18\r \x01(\rR\tunknown13\x12\x1d\n" +
	"\n" +
	"unknown_14\x18\x0e \x01(\rR\tunknown14\x12\x1d\n" +
	"\n" +
	"soul_level\x18\x0f \x01(\rR\tsoulLevel\x12\x1d\n" +
	"\n" +
	"unknown_16\x18\x10 \x01(\rR\tunknown16\x12\x1d\n" +
	"\n" +
	"unknown_17\x18\x11 \x01(\rR\tunknown17\x12*\n" +
	"\x11play_time_seconds\x18\x12 \x01(\rR\x0fplayTimeSeconds\x12\x1f\n" +
	"\vsoul_memory\x18\x13 \x01(\rR\n" +
	"soulMemory\x12\x1d\n" +
	"\n" +
	"unknown_20\x18\x14 \x01(\rR\tunknown20\x12\x1d\n" +
	"\n" +
	"unknown_21\x18\x15 \x01(\tR\tunknown21\"/\n" +
	"\x10ServerSideStatus\x12\x1b\n" +
	"\tunknown_1\x18\x01 \x01(\rR\bunknown1\"^\n" +
	"\x18StatsInfo_Bonfire_levels\x12\x1d\n" +
	"\n" +
	"bonfire_id\x18\x01 \x01(\rR\tbonfireId\x12#\n" +
	"\rbonfire_level\x18\x02 \x01(\rR\fbonfireLevel\"\xdb\a\n" +
	"\tStatsInfo\x12\x1b\n" +
	"\tunknown_1\x18\x01 \x01(\rR\bunknown1\x12\x1b\n" +
	"\tunknown_2\x18\x02 \x01(\rR\bunknown2\x12#\n" +
	"\rsinner_points\x18\x03 \x01(\rR\fsinnerPoints\x12T\n" +
	"\x0ebonfire_levels\x18\x04 \x03(\v2-.DS2_Frpg2PlayerData.StatsInfo_Bonfire_levelsR\rbonfireLevels\x12\x1b\n" +
	"\tunknown_5\x18\x05 \x01(\rR\bunknown5\x12V\n" +
	"\x14phantom_type_count_6\x18\x06 \x03(\v2%.DS2_Frpg2PlayerData.PhantomTypeCountR\x11phantomTypeCount6\x12V\n" +
	"\x14phantom_type_count_7\x18\a \x03(\v2%.DS2_Frpg2PlayerData.PhantomTypeCountR\x11phantomTypeCount7\x12V\n" +
	"\x14phantom_type_count_8\x18\b \x03(\v2%.DS2_Frpg2PlayerData.PhantomTypeCountR\x11phantomTypeCount8\x12V\n" +
	"\x14phantom_type_count_9\x18\t \x03(\v2%.DS2_Frpg2PlayerData.PhantomTypeCountR\x11phantomTypeCount9\x12\x1d\n" +
	"\n" +
	"unknown_10\x18\n" +
	" \x01(\rR\tunknown10\x12\x1d\n" +
	"\n" +
	"unknown_11\x18\v \x03(\rR\tunknown11\x12\x1d\n" +
	"\n" +
	"unknown_12\x18\f \x01(\rR\tunknown12\x12\x1d\n" +
	"\n" +
	"unknown_13\x18\r \x01(\rR\tunknown13\x12\x1d\n" +
	"\n" +
	"unknown_14\x18\x0e \x01(\rR\tunknown14\x12\x1d\n" +
	"\n" +
	"unknown_15\x18\x0f \x01(\rR\tunknown15\x12\x1d\n" +
	"\n" +
	"unknown_16\x18\x10 \x01(\rR\tunknown16\x129\n" +
	"\bdatetime\x18\x11 \x01(\v2\x1d.DS2_Frpg2PlayerData.DateTimeR\bdatetime\x12\x1d\n" +
	"\n" +
	"unknown_18\x18\x12 \x01(\rR\tunknown18\x12+\n" +
	"\x11unlocked_bonfires\x18\x13 \x03(\rR\x10unlockedBonfires\x12\x1d\n" +
	"\n" +
	"unknown_20\x18\x14 \x01(\rR\tunknown20\x12\x1d\n" +
	"\n" +
	"unknown_21\x18\x15 \x03(\rR\tunknown21\"2\n" +
	"\x06Vector\x12\f\n" +
	"\x01x\x18\x01 \x02(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x02(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x02(\x02R\x01z\"\xbc\x01\n" +
	"\fWeaponStatus\x12\x1a\n" +
	"\tleft_ar_1\x18\x01 \x01(\rR\aleftAr1\x12\x1a\n" +
	"\tleft_ar_2\x18\x02 \x01(\rR\aleftAr2\x12\x1a\n" +
	"\tleft_ar_3\x18\x03 \x01(\rR\aleftAr3\x12\x1c\n" +
	"\n" +
	"right_ar_1\x18\x04 \x01(\rR\brightAr1\x12\x1c\n" +
	"\n" +
	"right_ar_2\x18\x05 \x01(\rR\brightAr2\x12\x1c\n" +
	"\n" +
	"right_ar_3\x18\x06 \x01(\rR\brightAr3B\xcf\x01\n" +
	"\x17com.DS2_Frpg2PlayerDataB\x17DS2Frpg2PlayerDataProtoH\x01P\x01Z1github.com/sstreight/dso/internal/proto/ds2datapb\xa2\x02\x03DXX\xaa\x02\x12DS2Frpg2PlayerData\xca\x02\x12DS2Frpg2PlayerData\xe2\x02\x1eDS2Frpg2PlayerData\\GPBMetadata\xea\x02\x12DS2Frpg2PlayerData"

var (
	file_DS2_Frpg2PlayerData_proto_rawDescOnce sync.Once
	file_DS2_Frpg2PlayerData_proto_rawDescData []byte
)

func file_DS2_Frpg2PlayerData_proto_rawDescGZIP() []byte {
	file_DS2_Frpg2PlayerData_proto_rawDescOnce.Do(func() {
		file_DS2_Frpg2PlayerData_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_DS2_Frpg2PlayerData_proto_rawDesc), len(file_DS2_Frpg2PlayerData_proto_rawDesc)))
	})
	return file_DS2_Frpg2PlayerData_proto_rawDescData
}

var file_DS2_Frpg2PlayerData_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_DS2_Frpg2PlayerData_proto_goTypes = []any{
	(*AllStatus)(nil),                   // 0: DS2_Frpg2PlayerData.AllStatus
	(*ArmorStatus)(nil),                 // 1: DS2_Frpg2PlayerData.ArmorStatus
	(*DateTime)(nil),                    // 2: DS2_Frpg2PlayerData.DateTime
	(*EquipmentInfo)(nil),               // 3: DS2_Frpg2PlayerData.EquipmentInfo
	(*ItemUsingInfo)(nil),               // 4: DS2_Frpg2PlayerData.ItemUsingInfo
	(*LevelStatus)(nil),                 // 5: DS2_Frpg2PlayerData.LevelStatus
	(*PhantomTypeCount)(nil),            // 6: DS2_Frpg2PlayerData.PhantomTypeCount
	(*PhysicalStatus)(nil),              // 7: DS2_Frpg2PlayerData.PhysicalStatus
	(*PlayerLocation)(nil),              // 8: DS2_Frpg2PlayerData.PlayerLocation
	(*PlayerStatus_PhantomLeaveAt)(nil), // 9: DS2_Frpg2PlayerData.PlayerStatus_Phantom_leave_at
	(*PlayerStatus)(nil),                // 10: DS2_Frpg2PlayerData.PlayerStatus
	(*ServerSideStatus)(nil),            // 11: DS2_Frpg2PlayerData.ServerSideStatus
	(*StatsInfo_BonfireLevels)(nil),     // 12: DS2_Frpg2PlayerData.StatsInfo_Bonfire_levels
	(*StatsInfo)(nil),                   // 13: DS2_Frpg2PlayerData.StatsInfo
	(*Vector)(nil),                      // 14: DS2_Frpg2PlayerData.Vector
	(*WeaponStatus)(nil),                // 15: DS2_Frpg2PlayerData.WeaponStatus
}
var file_DS2_Frpg2PlayerData_proto_depIdxs = []int32{
	8,  // 0: DS2_Frpg2PlayerData.AllStatus.player_location:type_name -> DS2_Frpg2PlayerData.PlayerLocation
	10, // 1: DS2_Frpg2PlayerData.AllStatus.player_status:type_name -> DS2_Frpg2PlayerData.PlayerStatus
	4,  // 2: DS2_Frpg2PlayerData.AllStatus.item_using_info:type_name -> DS2_Frpg2PlayerData.ItemUsingInfo
	13, // 3: DS2_Frpg2PlayerData.AllStatus.stats_info:type_name -> DS2_Frpg2PlayerData.StatsInfo
	5,  // 4: DS2_Frpg2PlayerData.AllStatus.attributes:type_name -> DS2_Frpg2PlayerData.LevelStatus
	7,  // 5: DS2_Frpg2PlayerData.AllStatus.physical_status:type_name -> DS2_Frpg2PlayerData.PhysicalStatus
	15, // 6: DS2_Frpg2PlayerData.AllStatus.weapon_status:type_name -> DS2_Frpg2PlayerData.WeaponStatus
	1,  // 7: DS2_Frpg2PlayerData.AllStatus.armor_status:type_name -> DS2_Frpg2PlayerData.ArmorStatus
	11, // 8: DS2_Frpg2PlayerData.AllStatus.server_side_status:type_name -> DS2_Frpg2PlayerData.ServerSideStatus
	3,  // 9: DS2_Frpg2PlayerData.AllStatus.equipment_info:type_name -> DS2_Frpg2PlayerData.EquipmentInfo
	14, // 10: DS2_Frpg2PlayerData.PlayerLocation.position:type_name -> DS2_Frpg2PlayerData.Vector
	2,  // 11: DS2_Frpg2PlayerData.PlayerStatus_Phantom_leave_at.datetime:type_name -> DS2_Frpg2PlayerData.DateTime
	9,  // 12: DS2_Frpg2PlayerData.PlayerStatus.phantom_leave_at:type_name -> DS2_Frpg2PlayerData.PlayerStatus_Phantom_leave_at
	12, // 13: DS2_Frpg2PlayerData.StatsInfo.bonfire_levels:type_name -> DS2_Frpg2PlayerData.StatsInfo_Bonfire_levels
	6,  // 14: DS2_Frpg2PlayerData.StatsInfo.phantom_type_count_6:type_name -> DS2_Frpg2PlayerData.PhantomTypeCount
	6,  // 15: DS2_Frpg2PlayerData.StatsInfo.phantom_type_count_7:type_name -> DS2_Frpg2PlayerData.PhantomTypeCount
	6,  // 16: DS2_Frpg2PlayerData.StatsInfo.phantom_type_count_8:type_name -> DS2_Frpg2PlayerData.PhantomTypeCount
	6,  // 17: DS2_Frpg2PlayerData.StatsInfo.phantom_type_count_9:type_name -> DS2_Frpg2PlayerData.PhantomTypeCount
	2,  // 18: DS2_Frpg2PlayerData.StatsInfo.datetime:type_name -> DS2_Frpg2PlayerData.DateTime
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_DS2_Frpg2PlayerData_proto_init() }
func file_DS2_Frpg2PlayerData_proto_init() {
	if File_DS2_Frpg2PlayerData_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_DS2_Frpg2PlayerData_proto_rawDesc), len(file_DS2_Frpg2PlayerData_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DS2_Frpg2PlayerData_proto_goTypes,
		DependencyIndexes: file_DS2_Frpg2PlayerData_proto_depIdxs,
		MessageInfos:      file_DS2_Frpg2PlayerData_proto_msgTypes,
	}.Build()
	File_DS2_Frpg2PlayerData_proto = out.File
	file_DS2_Frpg2PlayerData_proto_goTypes = nil
	file_DS2_Frpg2PlayerData_proto_depIdxs = nil
}
